title: "Juan Cruz Targon"
description:
  <p align="center">
  Barcelona, Spain
  <br> (+34) 600551568 
  <br> juantargon@gmail.com
  <br> <a href="pdf/Carbone_Giorgio_CV_eng.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/juan-cruz-targon-93a876228/">LinkedIn</a>
  </p>
  <p align="justify">
  I am a <b>Data Engineer</b> with experience in <b>data ingestion, modeling, and processing</b> across Big Data and cloud environments, focused on building efficient, scalable, and high-quality data solutions.
  <br><br>
  I previously worked at <b>Santander Tecnología</b> (via Datalytics) and <b>Disbyte</b>, where I developed and optimized end-to-end data pipelines using technologies such as <b>PySpark, Airflow, SQL, AWS, and Python</b>. My work centered on improving performance, ensuring data reliability, and enabling business-driven analytics.
  <br><br>
  I hold a degree in <b>Information Systems Engineering</b> and I am currently pursuing a <b>Master’s in Economics, Finance, and Computation</b> at UNIA, integrating Big Data, applied economics, and AI-driven analysis.
  <br><br>
  Throughout my career, I have worked closely with engineering and business teams, contributing to data architecture design, defining modeling standards, and enhancing data quality and traceability across systems.
  <br><br>
  I am a committed, analytical, and proactive professional, passionate about leveraging data engineering, cloud technologies, and automation to solve complex problems and support data-driven decision-making.
  <br><br>
  </p>
author: "Juan Cruz Targon"

# Theme
theme: jekyll-theme-minimal

# Show download button for the repo (optional)
#show_downloads: true

# Your profile image (put the image in /assets/profile.jpg for example)
logo: /assets/profile.jpg

# Favicon (also place in /assets/)
favicon: /assets/favicon.png

# Social links (appear in the sidebar)
social_links:
  linkedin: "https://www.linkedin.com/in/juan-cruz-targon"
  github: "https://github.com/juancruztargon"
  email: "mailto:juantargon@gmail.com"

# Navigation bar (custom menu)
nav:
  - name: "Home"
    link: "/"
 # - name: "Projects"
    #link: "/projects"
  #- name: "CV"
  #  link: "/cv"
 # - name: "Contact"
 #   link: "/contact"

# Optional Google Analytics
#google_analytics: ""

# Markdown options
markdown: kramdown

# Plugins for better SEO and structure
plugins:
  - jekyll-seo-tag

# Build settings
exclude:
  - "README.md"
