title: "Juan Cruz Targon"
description:
  <p align="center">
  Barcelona, Spain
  <br> (+34) 600551568 
  <br> juantargon@gmail.com
  <br> <a href="pdf/Carbone_Giorgio_CV_eng.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/juan-cruz-targon-93a876228/">LinkedIn</a>
  <p align="justify">
  I am a <b>Data Engineer</b> with experience in data ingestion, modeling, and pipeline development across Big Data and cloud environments. I have worked at <b>Santander Tecnología</b> and <b>Disbyte</b>, focusing on scalable ETL/ELT processes, data quality, and performance optimization using <b>Python, PySpark, Airflow, SQL, and AWS</b>.
  <br><br>
  I hold a degree in <b>Information Systems Engineering</b> and I am currently pursuing a <b>Master’s in Economics, Finance, and Computation</b>, combining analytics, Big Data, and applied AI.
  <br><br>
  I enjoy solving complex problems, designing efficient data architectures, and enabling data-driven decision-making through high-quality engineering.
  </p>

author: "Juan Cruz Targon"

# Theme
theme: jekyll-theme-minimal

# Show download button for the repo (optional)
#show_downloads: true

# Your profile image (put the image in /assets/profile.jpg for example)
logo: /assets/profile.jpg

# Favicon (also place in /assets/)
favicon: /assets/favicon.png

# Social links (appear in the sidebar)
social_links:
  linkedin: "https://www.linkedin.com/in/juan-cruz-targon"
  github: "https://github.com/juancruztargon"
  email: "mailto:juantargon@gmail.com"

# Navigation bar (custom menu)
nav:
  - name: "Home"
    link: "/"
 # - name: "Projects"
    #link: "/projects"
  #- name: "CV"
  #  link: "/cv"
 # - name: "Contact"
 #   link: "/contact"

# Optional Google Analytics
#google_analytics: ""

# Markdown options
markdown: kramdown

# Plugins for better SEO and structure
plugins:
  - jekyll-seo-tag

# Build settings
exclude:
  - "README.md"
